Algorithms for supervised learning of penalty functions for
change-point detection

[[https://github.com/tdhock/penaltyLearning/actions][https://github.com/tdhock/penaltyLearning/workflows/R-CMD-check/badge.svg]]

This R package provides a practical implementation of the algorithms
described in our ICML'13 paper, [[http://jmlr.org/proceedings/papers/v28/hocking13.html][Learning Sparse Penalties for
Change-point Detection using Max Margin Interval Regression]]. This
package can be used to learn a penalty function for predicting highly
accurate changepoints in labeled data sets such as [[https://cran.r-project.org/package=neuroblastoma][neuroblastoma]]. The
main advantage of this method is increased accuracy, relative to
unsupervised methods (such as information criteria: AIC, BIC, etc). In
particular, since we have labels that indicate where there should and
should not be changepoints, we can use them to learn a highly accurate
penalty function which minimizes the number of incorrectly predicted
labels. The learned penalty function can be used for predicting the
number of changepoints in other data (even in data without labels).

** Installation

From CRAN:

#+BEGIN_SRC R
install.packages("penaltyLearning")
#+END_SRC

From GitHub:

#+BEGIN_SRC R
if(!require(devtools))install.packages("devtools")
devtools::install_github("tdhock/penaltyLearning")
#+END_SRC

** Usage

See my useR2017 tutorial on [[https://tdhock.github.io/change-tutorial/Supervised.html][Supervised changepoint detection]] [[[https://channel9.msdn.com/events/useR-international-R-User-conferences/useR-International-R-User-2017-Conference/Introduction-to-optimal-changepoint-detection-algorithms-II?term%253Dhocking][video]]],
which explains how to use penaltyLearning in detail. [[[https://github.com/tdhock/change-tutorial][GitHub repo with
links to additional course materials]]]

